PrisonerMS/Models/Complaint.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PrisonerMS.Models
{
    public class Complaint
    {
        public int ComplaintID { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string DateRegister { get; set; }
        public string DateResolve { get; set; }
        public int PrisonerID { get; set; }
        public string PrisonerNo { get; set; }
        public string PrisonerName { get; set; }

    }
}

PrisonerMS/Models/Prisoner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PrisonerMS.Models
{
    public class Prisoner
    {
        public int PrisonerID { get; set; }
        public string PrisonerNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public char Gender { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string DateBirth { get; set; }
        public string VisitingDay { get; set; }
        public string VisitingTime { get; set; }
        public string DateEntry { get; set; }
        public Cell Cell { get; set; }
        public Prison Prison { get; set; }
    }
}

PrisonerMS/Models/Transfer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PrisonerMS.Models
{
    public class Transfer
    {
        public int TransferID { get; set; }
        public string Type { get; set; }
        public string TypeNumber { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryTime { get; set; }
        public Prisoner Prisoner { get; set; }
        public Prison Prison { get; set; }

    }
}

PrisonerMS/Models/Visitor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PrisonerMS.Models
{
    public class Visitor
    {
        public int VisitorRecordID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string Relation { get; set; }
        public string VisitDate { get; set; }
        public string VisitTime { get; set; }
        public Prisoner Prisoner { get; set; }
        public Prison Prison { get; set; }
    }
}

PrisonerMS/Controllers/JailOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PrisonerMS.Models;
using System.Web.Mvc;

namespace PrisonerMS.Controllers
{
    public class JailOController : Controller
    {
        // GET: JailO
        public ActionResult DashBoard()
        {
            return View(new Tuple<List<Transfer>, List<Transfer>>(TransferCRUD.GetIncomingTransfers((int)Session["PrisonID"]), TransferCRUD.GetDashBoardTransfers((int)Session["PrisonID"])));
        }

        public ActionResult Prisoners()
        {
            return View(PrisonerCRUD.GetAllPrisonPrisoners((int)Session["PrisonID"]));
        }

        public ActionResult Complaints()
        {
            return View(ComplaintCRUD.GetAllComplaints());
        }

        public ActionResult Visitors()
        {
            return View(VisitorCRUD.GetAllPrisonVisitors((int)Session["PrisonID"]));
        }

        public ActionResult Transfers()
        {
            return View(TransferCRUD.GetAllPrisonTransfers((int)Session["PrisonID"]));
        }

        public ActionResult PrisonInfo()
        {
            return View();
        }

        public ActionResult PrisonerDetails(int id)
        {
            return View(new Tuple<Prisoner, List<Punishment>>(PrisonerCRUD.GetPrisoner(id), PunishmentCRUD.GetAllPunishments()));
        }

        public ActionResult UserInfo()
        {
            return View();
        }


        //Load Extend
        public ActionResult MedicalRecords(int id)
        {
            List<Medical> mrList = MedicalCRUD.GetAllPrisonerMedicals(id);
            List<Medication> mList = new List<Medication>();
            List<Allergy> aList = new List<Allergy>();

            foreach (Medical mr in mrList)
            {
                mList.AddRange(MedicationCRUD.GetAllMedicalMedications(mr.MedicalID));
                aList.AddRange(AllergyCRUD.GetAllMedicalAllergys(mr.MedicalID));
            }

            return PartialView("_MedicalRecords", new Tuple<List<Medical>, List<Medication>, List<Allergy>>(mrList, mList, aList));
        }


        //Detail
        public ActionResult DetailVisitor(int id)
        {
            return PartialView("_DetailVisitor", VisitorCRUD.GetVisitor(id));
        }

        public ActionResult DetailTransfer(int id)
        {
            return PartialView("_DetailTransfer", TransferCRUD.GetTransfer(id));
        }

        public ActionResult DetailMedical(int id)
        {
            Medical m = MedicalCRUD.GetMedical(id);
            List<Medication> mList = MedicationCRUD.GetAllMedicalMedications(id);
            List<Allergy> aList = AllergyCRUD.GetAllMedicalAllergys(id);

            return PartialView("_DetailMedical", new Tuple<Medical, List<Medication>, List<Allergy>>(m, mList, aList));
        }


        //Edit
        public ActionResult EditPrisoner(int id)
        {
            Prisoner ptemp = PrisonerCRUD.GetPrisoner(id);
            return PartialView("_EditPrisoner", ptemp);
        }

        public ActionResult EditVisitor(int id)
        {
            Visitor visitor = VisitorCRUD.GetVisitor(id);
            return PartialView("_EditVisitor", visitor);
        }

        public ActionResult EditTransfer(int id)
        {
            return PartialView("_EditTransfer", TransferCRUD.GetTransfer(id));
        }

        public ActionResult EditMedical(int id)
        {
            return PartialView("_EditMedical", MedicalCRUD.GetMedical(id));
        }

        public ActionResult EditMedication(int id)
        {
            return PartialView("_EditMedication", MedicationCRUD.GetMedication(id));
        }

        public ActionResult EditAllergy(int id)
        {
            return PartialView("_EditAllergy", AllergyCRUD.GetAllergy(id));
        }


        //Add
        public ActionResult AddComplaint(int id)
        {
            return PartialView("_AddComplaint", 1);
        }

        public ActionResult AddVisitor(int id)
        {
            return PartialView("_AddVisitor", id);
        }

        public ActionResult AddTransfer(int id)
        {
            return PartialView("_AddTransfer", id);
        }

        public ActionResult AddMedication(int id)
        {
            return PartialView("_AddMedication", id);
        }

        public ActionResult AddAllergy(int id)
        {
            return PartialView("_AddAllergy", id);
        }


        //Form
        [HttpPost]
        public ActionResult AddVisitorForm(FormCollection collection)
        {
            Visitor visitor = new Visitor();
            visitor.FirstName = collection["FirstName"];
            visitor.LastName = collection["LastName"];
            visitor.Gender = collection["Gender"];
            visitor.CNIC = collection["CNIC"];
            visitor.Address = collection["Address"];
            visitor.Relation = collection["Relation"];
            visitor.Prisoner = new Prisoner();
            visitor.Prisoner.PrisonerID = Int32.Parse(collection["PrisonerID"]);
            visitor.Prison = new Prison();
            visitor.Prison.PrisonID = (int)Session["PrisonID"];

            if (VisitorCRUD.InsertVisitor(visitor))
                return Content("<script>alert('Visitor Added Successfully.');window.location.href=document.referrer;</script>");
            else
                return Content("<script>alert('Visitor could not be Added');window.location.href=document.referrer</script>");
        }

        [HttpPost]
        public ActionResult EditVisitorForm(FormCollection collection)
        {
            Visitor visitor = new Visitor();
            visitor.FirstName = collection["FirstName"];
            visitor.LastName = collection["LastName"];
            visitor.Gender = collection["Gender"];
            visitor.CNIC = collection["CNIC"];
            visitor.Address = collection["Address"];
            visitor.Relation = collection["Relation"];
            visitor.VisitorRecordID = Int32.Parse(collection["VisitorID"]);

            if (VisitorCRUD.UpdateVisitor(visitor))
                return Content("<script>alert('Visiter Info Updated Successfully.');window.location.href=document.referrer;</script>");
            else
                return Content("<script>alert('Visitor Info could not be Updated');window.location.href=document.referrer</script>");
        }

        [HttpPost]
        public ActionResult AddTransferForm(FormCollection collection)
        {
            Transfer transfer = new Transfer();
            transfer.Type = collection["Type"];
            transfer.Description = collection["Desc"];
            transfer.Prisoner = new Prisoner();
            transfer.Prisoner.PrisonerID = Int32.Parse(collection["PrisonerID"]);
            transfer.Status = "InProgress";
            transfer.Prison = new Prison();
            transfer.Prison.PrisonID = (int)Session["PrisonID"];

            if (transfer.Type.Equals("Prison"))
                transfer.TypeNumber = collection["TypeNumber"];
            else
                transfer.TypeNumber = "-";

            if (TransferCRUD.InsertTransfer(transfer))
                return Content("<script>alert('Transfer Added Successfully.');window.location.href=document.referrer;</script>");
            else
                return Content("<script>alert('Transfer could not be Updated');window.location.href=document.referrer</script>");
        }

        [HttpPost]
        public ActionResult EditTransferForm(FormCollection collection)
        {
            Transfer transfer = new Transfer();
            transfer.Description = collection["Desc"];
            transfer.TransferID = Int32.Parse(collection["TransferID"]);

            if (TransferCRUD.UpdateTransfer(transfer))
                return Content("<script>alert('Transfer Updated Successfully.');window.location.href=document.referrer;</script>");
            else
                return Content("<script>alert('Transfer could not be Updated');window.location.href=document.referrer</script>");
        }

        [HttpPost]
        public ActionResult StatusTransferForm(FormCollection collection)
        {
            Transfer transfer = new Transfer();
            transfer.Status = collection["TransferStatus"];
            transfer.TransferID = Int32.Parse(collection["TransferID"]);

            if (TransferCRUD.UpdateStatusTransfer(transfer))
                return Content("<script>alert('Transfer Status Updated Successfully.');window.location.href=document.referrer;</script>");
            else
                return Content("<script>alert('Transfer Status could not be Updated');window.location.href=document.referrer</script>");
        }

        [HttpPost]
        public ActionResult AddMedicalForm(FormCollection collection)
        {
            Medical medical = new Medical();
            medical.Symptoms = collection["Symptoms"];
            medical.Diagnosis = collection["Diagnosis"];
            medical.Prisoner = new Prisoner();
            medical.Prisoner.PrisonerID = Int32.Parse(collection["PrisonerID"]);

            if (MedicalCRUD.InsertMedical(medical))
                return Content("<script>alert('Medical Added Successfully.');window.location.href=document.referrer;</script>");
            else
                return Content("<script>alert('Medical could not be Added');window.location.href=document.referrer</script>");
        }

        [HttpPost]
        public ActionResult EditMedicalForm(FormCollection collection)
        {
            Medical medical = new Medical();
            medical.Symptoms = collection["Symptoms"];
            medical.Diagnosis = collection["Diagnosis"];
            medical.MedicalID = Int32.Parse(collection["MedicalID"]);

            if (MedicalCRUD.UpdateMedical(medical))
                return Content("<script>alert('Medical Updated Successfully.');window.location.href=document.referrer;</script>");
            else

PrisonerMS/Views/JailO/Complaints.cshtml
@{
    ViewBag.Title = "Complaints";
}

@model List<PrisonerMS.Models.Complaint>

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jail Officer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "JailO")">DashBoard</a>
            <a href="@Url.Action("Prisoners", "JailO")">Prisoners</a>
            <a href="@Url.Action("Complaints", "JailO")">Complaints</a>
            <a href="@Url.Action("Visitors", "JailO")">Visitors</a>
            <a href="@Url.Action("Transfers", "JailO")">Transfers</a>
            <a href="@Url.Action("PrisonInfo", "JailO")">Prison Info</a>
            <a href="@Url.Action("UserInfo", "JailO")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Complaints</h3>
        <hr class="hunderline" />

        @if (Model != null)
        {
            <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0">
                <tr>
                    <th>Number</th>
                    <th>Status</th>
                    <th>Description</th>
                    <th>Register Date</th>
                    <th>Resolve Date</th>
                    <th>Priosner No</th>
                    <th>Prisoner Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><a href=" ../../JailO/ComplaintDetails?id=@item.ComplaintID">@item.ComplaintID</a></td>
                        <td>@item.Status</td>
                        <td>@item.Description</td>
                        <td>@item.DateRegister</td>
                        <td>@item.DateResolve</td>
                        <td><a href=" ../../JailO/PrisonerDetails?id=@item.PrisonerID">@item.PrisonerNo</a></td>
                        <td>@item.PrisonerName</td>
                        <td><a href="#" class="btn btn-success" onclick="ComplaintStatusfunction(@item.ComplaintID)"><i class="fa fa-pencil-square-o"></i> </a> </td>
                        <td><a href="../../Home/ErrorImplementation" class="btn btn-danger"><i class="fa fa-trash"></i> </a> </td>
                    </tr>
                }
            </table>
        }

        <div class="modal fade" id="changeStatusModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Change Complaint Status</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="changeStatusModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>

    var ComplaintStatusfunction = function (cid) {

        var url = "/JailO/ComplaintStatus?id=" + cid;

        $("#changeStatusModalBodyDiv1").load(url, function () {
            $("#changeStatusModal").modal("show");

        })
    }

</script>

PrisonerMS/Views/JailO/PrisonInfo.cshtml
@{
    ViewBag.Title = "Prison Info";
}

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jail Officer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "JailO")">DashBoard</a>
            <a href="@Url.Action("Prisoners", "JailO")">Prisoners</a>
            <a href="@Url.Action("Complaints", "JailO")">Complaints</a>
            <a href="@Url.Action("Visitors", "JailO")">Visitors</a>
            <a href="@Url.Action("Transfers", "JailO")">Transfers</a>
            <a href="@Url.Action("PrisonInfo", "JailO")">Prison Info</a>
            <a href="@Url.Action("UserInfo", "JailO")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Visitors</h3>
        <hr class="hunderline" />

        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0">
            <tr>
                <th>Cell Number</th>
                <th>Prisoner Number</th>
                <th>Prisoner Name</th>
            </tr>
            <tr>
                <td>25D</td>
                <td>5555</td>
                <td>Muhammad Sikandar</td>
            </tr>
            <tr>
                <td>26D</td>
                <td>6666</td>
                <td>Asad Khalil</td>
            </tr>
            <tr>
                <td>27D</td>
                <td>7777</td>
                <td>Hamza Jawad</td>
            </tr>
            <tr>
                <td>28D</td>
                <td>8888</td>
                <td>Talal Waseem</td>
            </tr>
        </table>

    </div>
</div>

PrisonerMS/Views/JailO/Transfers.cshtml
@{
    ViewBag.Title = "Transfers";
}

@model List<PrisonerMS.Models.Transfer>

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jail Officer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "JailO")">DashBoard</a>
            <a href="@Url.Action("Prisoners", "JailO")">Prisoners</a>
            <a href="@Url.Action("Complaints", "JailO")">Complaints</a>
            <a href="@Url.Action("Visitors", "JailO")">Visitors</a>
            <a href="@Url.Action("Transfers", "JailO")">Transfers</a>
            <a href="@Url.Action("PrisonInfo", "JailO")">Prison Info</a>
            <a href="@Url.Action("UserInfo", "JailO")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Transfers History</h3>
        <hr class="hunderline" />

        @if (Model != null)
        {
            <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0">
                <tr>
                    <th>Number</th>
                    <th>Type</th>
                    <th>Type Number</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Entry Date</th>
                    <th>Priosner No</th>
                    <th>Prisoner Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><a href="#" onclick="DetailTransferfunction(@item.TransferID)">@item.TransferID</a></td>
                        <td>@item.Type</td>
                        <td>@item.TypeNumber</td>
                        <td>@item.Description</td>
                        <td>@item.Status</td>
                        <td>@item.EntryDate</td>
                        <td><a href=" ../../JailO/PrisonerDetails?id=@item.Prisoner.PrisonerID">@item.Prisoner.PrisonerNo</a></td>
                        <td>@item.Prisoner.FirstName @item.Prisoner.LastName</td>
                        <td><a href="#" class="btn btn-success" onclick="EditTransferfunction(@item.TransferID)"><i class="fa fa-pencil-square-o"></i> </a> </td>
                        <td><a href=" ../../JailO/RemoveTransfer?id=@item.TransferID" class="btn btn-danger"><i class="fa fa-trash"></i> </a> </td>
                    </tr>
                }
            </table>
        }

        <div class="modal fade" id="detailTransferModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Transfer Detail</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="detailTransferModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="editTransferModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Add Transfer</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="editTransferModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>

    var DetailTransferfunction = function (tid) {

        var url = "/JailO/DetailTransfer?id=" + tid;

        $("#detailTransferModalBodyDiv1").load(url, function () {
            $("#detailTransferModal").modal("show");

        })
    }

    var EditTransferfunction = function (vid) {

        var url = "/JailO/EditTransfer?id=" + vid;

        $("#editTransferModalBodyDiv1").load(url, function () {
            $("#editTransferModal").modal("show");

        })
    }

</script>

PrisonerMS/Views/JailO/UserInfo.cshtml
@{
    ViewBag.Title = "UserInfo";
}

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jail Officer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "JailO")">DashBoard</a>
            <a href="@Url.Action("Prisoners", "JailO")">Prisoners</a>
            <a href="@Url.Action("Complaints", "JailO")">Complaints</a>
            <a href="@Url.Action("Visitors", "JailO")">Visitors</a>
            <a href="@Url.Action("Transfers", "JailO")">Transfers</a>
            <a href="@Url.Action("PrisonInfo", "JailO")">Prison Info</a>
            <a href="@Url.Action("UserInfo", "JailO")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Profile</h3>
        <hr class="hunderline" />

        <p><strong>Username : </strong> asad <p>
            <button href="#" type="button" class="btn btn-info" onclick="location.href='@Url.Action("ErrorImplementation", "Home")'">Change Password</button>


            <h3 class="divheading text-center">Personal Info</h3>
            <hr class="hunderline" />

        <p><strong>Name : </strong> Asad Khalil</p>
        <p><strong>Gender : </strong> Male </p>
        <p><strong>Contact : </strong>03004112112</p>
        <p><strong>DateJoined : </strong>11/11/2019</p>
        <p><strong>Account Status : </strong>Jail Officer</p>
        <button href="#" type="button" class="btn btn-success" onclick="location.href='@Url.Action("ErrorImplementation", "Home")'">Edit Info</button>


        <div class="modal fade" id="changePasswordModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Change Password</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="changePasswordModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="editInfoModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Edit Profile Info</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="editInfoModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>


<script>
    var PasswordChangefunction = function (bid) {

        var url = "/JailO/PasswordChange?id=" + bid;

        $("#changePasswordModalBodyDiv1").load(url, function () {
            $("#changePasswordModal").modal("show");

        })
    }

    var EditInfofunction = function (uid) {

        var url = "/JailO/EditInfo?id=" + uid;

        $("#editInfoModalBodyDiv1").load(url, function () {
            $("#editInfoModal").modal("show");

        })
    }
</script>

PrisonerMS/Views/JailO/_AddAllergy.cshtml
@model int

<div>
    <div class="card rounded px-5 py-2">
        <div class="card-body">
            <form onsubmit="return CheckDescription(this)" action="AddAllergyForm" class="form needs-validation" role="form" autocomplete="off" method="post">

                <input type="hidden" class="form-control" id="C_MID" name="MedicalID" value="@Model" required />

                <div class="form-group">
                    <label for="C_Desc">Description</label>
                    <input type="text" class="form-control" placeholder="Enter Description" id="C_Desc" name="Desc" required>
                    <div class="invalid-feedback">Please enter valid input</div>
                </div>

                <div>
                    <button type="submit" class="btn btn-success btn-block" onclick="return CheckDescription(Desc)">Done</button>
                </div>

            </form>
        </div>
    </div>
</div>

<!--Javascript Validation-->
<script>
    function CheckDescription(inputtxt) {
        var notallowed1 = /^[0-9 ]+$/;
        var notallowed2 = /^[()-[] ]+$/;
        var notallowed3 = /^[0-9()-_ ]+$/;
        var allowed1 = /^[a-z ]+$/i;
        var allowed2 = /^[a-z0-9 ]+$/i;
        var allowed3 = /^[a-z() ]+$/i;
        var allowed4 = /^[a-z0-9() ]+$/i;
        if ((!(inputtxt.value.match(notallowed1) || inputtxt.value.match(notallowed2) || inputtxt.value.match(notallowed3))) && (inputtxt.value.match(allowed1) || inputtxt.value.match(allowed2) || inputtxt.value.match(allowed3) || inputtxt.value.match(allowed4))) {
            return true;
        }
        else {
            alert('Invalid Description. Please enter either alphanumeric or string data');
            var myElement = document.getElementById("C_Desc");
            myElement.value = "";
            return false;
        }
    }
</script>

PrisonerMS/Views/JailO/_AddComplaint.cshtml
@model int

<div>
    <div class="card rounded px-5 py-2">
        <div class="card-body">
            <form onsubmit="return CheckDescription(this)" action="ErrorImp" class="form needs-validation" role="form" autocomplete="off" method="post">

                <input type="hidden" class="form-control" id="C_CompID" name="ComplaintID" value=@Model required />

                <div class="form-group">
                    <label for="C_Desc">Description</label>
                    <input type="text" class="form-control" placeholder="Enter Description" id="C_Desc" name="Description" required>
                    <div class="invalid-feedback">Please enter valid input</div>
                </div>

                <div>
                    <button type="submit" class="btn btn-success btn-block" onclick="return CheckDescription(Description)">Done</button>
                </div>

            </form>
        </div>
    </div>
</div>

<!--Javascript Validation-->
<script>
    function CheckDescription(inputtxt) {
        var notallowed1 = /^[0-9 ]+$/;
        var notallowed2 = /^[()-[] ]+$/;
        var notallowed3 = /^[0-9()-_ ]+$/;
        var allowed1 = /^[a-z ]+$/i;
        var allowed2 = /^[a-z0-9 ]+$/i;
        var allowed3 = /^[a-z() ]+$/i;
        var allowed4 = /^[a-z0-9() ]+$/i;
        if ((!(inputtxt.value.match(notallowed1) || inputtxt.value.match(notallowed2) || inputtxt.value.match(notallowed3))) && (inputtxt.value.match(allowed1) || inputtxt.value.match(allowed2) || inputtxt.value.match(allowed3) || inputtxt.value.match(allowed4))) {
            return true;
        }
        else {
            alert('Invalid Description. Please enter either alphanumeric or string data');
            var myElement = document.getElementById("C_Desc");
            myElement.value = "";
            return false;
        }
    }
</script>