PrisonerMS/Models/Complaint.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PrisonerMS.Models
{
    public class Complaint
    {
        public int ComplaintID { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string DateRegister { get; set; }
        public string DateResolve { get; set; }
        public int PrisonerID { get; set; }
        public string PrisonerNo { get; set; }
        public string PrisonerName { get; set; }

    }
}

PrisonerMS/Models/Transfer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PrisonerMS.Models
{
    public class Transfer
    {
        public int TransferID { get; set; }
        public string Type { get; set; }
        public string TypeNumber { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryTime { get; set; }
        public Prisoner Prisoner { get; set; }
        public Prison Prison { get; set; }

    }
}

PrisonerMS/Controllers/JailerController.cs
using PrisonerMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrisonerMS.Controllers
{
    public class JailerController : Controller
    {
        // GET: Jailer
        public ActionResult DashBoard()
        {
            List<Complaint> AllComplaints = ComplaintCRUD.GetAllComplaints();
            AllComplaints.RemoveAll(item => item.Status == "Resolved");

            return View(new Tuple<List<Complaint>, List<Transfer>>(AllComplaints, TransferCRUD.GetAdminTransfers((int)Session["PrisonID"])));
        }

        public ActionResult Complaints()
        {
            return View(ComplaintCRUD.GetAllComplaints());
        }

        public ActionResult Transfers()
        {
            return View(TransferCRUD.GetAllPrisonTransfers((int)Session["PrisonID"]));
        }

        public ActionResult PrisonerDetails(int id)
        {
            return View(new Tuple<Prisoner, List<Punishment>>(PrisonerCRUD.GetPrisoner(id), PunishmentCRUD.GetAllPunishments()));
        }

        public ActionResult UserInfo()
        {
            return View();
        }


        //Load Extend
        public ActionResult MedicalRecords(int id)
        {
            List<Medical> mrList = MedicalCRUD.GetAllPrisonerMedicals(id);
            List<Medication> mList = new List<Medication>();
            List<Allergy> aList = new List<Allergy>();

            foreach (Medical mr in mrList)
            {
                mList.AddRange(MedicationCRUD.GetAllMedicalMedications(mr.MedicalID));
                aList.AddRange(AllergyCRUD.GetAllMedicalAllergys(mr.MedicalID));
            }

            return PartialView("_MedicalRecords", new Tuple<List<Medical>, List<Medication>, List<Allergy>>(mrList, mList, aList));
        }


        //Detail
        public ActionResult DetailTransfer(int id)
        {
            return PartialView("_DetailTransfer", TransferCRUD.GetTransfer(id));
        }

        public ActionResult DetailMedical(int id)
        {
            Medical m = MedicalCRUD.GetMedical(id);
            List<Medication> mList = MedicationCRUD.GetAllMedicalMedications(id);
            List<Allergy> aList = AllergyCRUD.GetAllMedicalAllergys(id);

            return PartialView("_DetailMedical", new Tuple<Medical, List<Medication>, List<Allergy>>(m, mList, aList));
        }


        //Form
        [HttpPost]
        public ActionResult StatusTransferForm(FormCollection collection)
        {
            Transfer transfer = new Transfer();
            transfer.Status = collection["TransferStatus"];
            transfer.TransferID = Int32.Parse(collection["TransferID"]);

            if (TransferCRUD.UpdateStatusTransfer(transfer))
                return Content("<script>alert('Transfer Status Updated Successfully.');window.location.href=document.referrer;</script>");
            else
                return Content("<script>alert('Transfer Status could not be Updated');window.location.href=document.referrer</script>");
        }


        //Status
        public ActionResult ComplaintStatus(int id)
        {
            return PartialView("_ComplaintStatus", id);
        }

        public ActionResult StatusTransfer(int id, int p)
        {
            return PartialView("_StatusTransfer", new Tuple<int, int>(id, p));
        }


    }
}

PrisonerMS/Views/Jailer/Complaints.cshtml
@{
    ViewBag.Title = "Complaints";
}

@model List<PrisonerMS.Models.Complaint>

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jailer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "Jailer")">DashBoard</a>
            <a href="@Url.Action("Complaints", "Jailer")">Complaints</a>
            <a href="@Url.Action("Transfers", "Jailer")">Transfers</a>
            <a href="@Url.Action("UserInfo", "Jailer")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Complaints</h3>
        <hr class="hunderline" />

        @if (Model != null)
        {
            <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0">
                <tr>
                    <th>Number</th>
                    <th>Status</th>
                    <th>Description</th>
                    <th>Register Date</th>
                    <th>Resolve Date</th>
                    <th>Priosner No</th>
                    <th>Prisoner Name</th>
                    <th>Change Status</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><a href=" ../../Jailer/ComplaintDetails?id=@item.ComplaintID">@item.ComplaintID</a></td>
                        <td>@item.Status</td>
                        <td>@item.Description</td>
                        <td>@item.DateRegister</td>
                        <td>@item.DateResolve</td>
                        <td><a href=" ../../Jailer/PrisonerDetails?id=@item.PrisonerID">@item.PrisonerNo</a></td>
                        <td>@item.PrisonerName</td>
                        <td><a href="#" class="btn btn-success" onclick="ComplaintStatusfunction(@item.ComplaintID)"><i class="fa fa-pencil-square-o"></i> </a> </td>
                    </tr>
                }
            </table>
        }

        <div class="modal fade" id="changeStatusModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Change Complaint Status</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="changeStatusModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>

    var ComplaintStatusfunction = function (cid) {

        var url = "/Jailer/ComplaintStatus?id=" + cid;

        $("#changeStatusModalBodyDiv1").load(url, function () {
            $("#changeStatusModal").modal("show");

        })
    }

</script>

PrisonerMS/Views/Jailer/DashBoard.cshtml
@{
    ViewBag.Title = "DashBoard";
}

@model Tuple<List<PrisonerMS.Models.Complaint>, List<PrisonerMS.Models.Transfer>>

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jailer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "Jailer")">DashBoard</a>
            <a href="@Url.Action("Complaints", "Jailer")">Complaints</a>
            <a href="@Url.Action("Transfers", "Jailer")">Transfers</a>
            <a href="@Url.Action("UserInfo", "Jailer")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Pending Complaints</h3>
        <hr class="hunderline" />

        @if (Model != null)
        {
            if (Model.Item1 != null && Model.Item1.Count != 0)
            {
                <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0">
                    <tr>
                        <th>Number</th>
                        <th>Status</th>
                        <th>Description</th>
                        <th>Register Date</th>
                        <th>Resolve Date</th>
                        <th>Priosner No</th>
                        <th>Prisoner Name</th>
                        <th>Status</th>
                    </tr>
                    @foreach (var item in Model.Item1)
                    {
                        <tr>
                            <td>@item.ComplaintID</td>@*<a href=" ../../Jailer/ComplaintDetails?id=@item.ComplaintID">@item.ComplaintID</a></td>*@
                            <td>@item.Status</td>
                            <td>@item.Description</td>
                            <td>@item.DateRegister</td>
                            <td>@item.DateResolve</td>
                            <td><a href=" ../../Jailer/PrisonerDetails?id=@item.PrisonerID">@item.PrisonerNo</a></td>
                            <td>@item.PrisonerName</td>
                            <td><a href="#" class="btn btn-success" onclick="ComplaintStatusfunction(@item.ComplaintID)"><i class="fa fa-pencil-square-o"></i> </a> </td>
                        </tr>
                    }
                </table>
            }
        }

        <div class="modal fade" id="changeStatusModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Change Complaint Status</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="changeStatusModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>


        <h3 class="divheading text-center">Pending Transfers</h3>
        <hr class="hunderline" />

        @if (Model != null)
        {
            if (Model.Item2 != null && Model.Item2.Count != 0)
            {
                <table id="example2" class="table table-striped table-bordered table-hover" cellspacing="0">
                    <tr>
                        <th>Number</th>
                        <th>Type</th>
                        <th>Type Number</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Entry Date</th>
                        <th>Priosner No</th>
                        <th>Prisoner Name</th>
                        <th>Status</th>
                    </tr>
                    @foreach (var item in Model.Item2)
                    {
                        <tr>
                            <td><a href="#" onclick="DetailTransferfunction(@item.TransferID)">@item.TransferID</a></td>
                            <td>@item.Type</td>
                            <td>@item.TypeNumber</td>
                            <td>@item.Description</td>
                            <td>@item.Status</td>
                            <td>@item.EntryDate</td>
                            <td><a href=" ../../JailO/PrisonerDetails?id=@item.Prisoner.PrisonerID">@item.Prisoner.PrisonerNo</a></td>
                            <td>@item.Prisoner.FirstName @item.Prisoner.LastName</td>
                            <td><a href="#" class="btn btn-success" onclick="StatusTransferfunction(@item.TransferID, '@item.Type')"><i class="fa fa-pencil-square-o"></i> </a> </td>
                        </tr>
                    }
                </table>
            }
        }

        <div class="modal fade" id="detailTransferModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Transfer Detail</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="detailTransferModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="changeTransferStatusModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Transfer Status</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="changeTransferStatusModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>

    var DetailTransferfunction = function (tid) {

        var url = "/Jailer/DetailTransfer?id=" + tid;

        $("#detailTransferModalBodyDiv1").load(url, function () {
            $("#detailTransferModal").modal("show");

        })
    }

    var ComplaintStatusfunction = function (cid) {

        var url = "/Jailer/ComplaintStatus?id=" + cid;

        $("#changeStatusModalBodyDiv1").load(url, function () {
            $("#changeStatusModal").modal("show");

        })
    }

    var StatusTransferfunction = function (tid, p) {

        para = 0
        if (p == 'Prison')
            para = 1
        var url = "/Jailer/StatusTransfer?id=" + tid + "&p=" + para;

        $("#changeTransferStatusModalBodyDiv1").load(url, function () {
            $("#changeTransferStatusModal").modal("show");

        })
    }

</script>

PrisonerMS/Views/Jailer/PrisonerDetails.cshtml
@{
    ViewBag.Title = "PrisonerDetails";
}

@model Tuple<PrisonerMS.Models.Prisoner, List<PrisonerMS.Models.Punishment>>

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jail Officer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}

<div class="container body-content">
    <h3 class="divheading text-center">Prisoner Details</h3>
    <hr class="hunderline" />

    <div class="card rounded px-5 py-2">
        <div class="card-body">
            @*<img class="float-right" src="">*@

            <h3>@Model.Item1.FirstName @Model.Item1.LastName</h3>
            <p><strong>Number: </strong>@Model.Item1.PrisonerNo</p>
            <p><strong>Gender: </strong>@Model.Item1.Gender</p>
            <p><strong>Father Name: </strong>@Model.Item1.FatherName</p>
            <p><strong>CNIC: </strong>@Model.Item1.CNIC</p>
            <p><strong>Adress: </strong>@Model.Item1.Address</p>
            <p><strong>Date of Birth: </strong>@Model.Item1.DateBirth</p>
            <p><strong>Visiting Day: </strong>@Model.Item1.VisitingDay</p>
            <p><strong>Visiting Time: </strong>@Model.Item1.VisitingTime</p>
            <p><strong>Cell Number: </strong>@Model.Item1.Cell.CellNo</p>
            <p><strong>Prison Number: </strong>@Model.Item1.Prison.PNumber</p>
            <p><strong>Prison Name: </strong>@Model.Item1.Prison.Name</p>
            <p><strong>Entry Date: </strong>@Model.Item1.DateEntry</p>

        </div>
    </div>

    <h3 class="divheading text-center my-2">Punishment History</h3>
    <hr class="hunderline" />

    <div class="card rounded px-2 py-2">
        <div class="card-body">

            @if (Model != null)
            {
                if (Model.Item2 != null && Model.Item2.Count != 0)
                {
                    <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0">
                        <tr>
                            <th>Type</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Execution Date</th>
                            <th>Notes</th>
                            <th>Prison Number</th>
                        </tr>
                        @foreach (var item in Model.Item2)
                        {
                            <tr>
                                <td>@item.Type</td>
                                <td>@item.DateStart</td>
                                <td>@item.DateEnd</td>
                                <td>@item.DateExecution</td>
                                <td>@item.Notes</td>
                                <td>@item.PrisonNumber</td>
                            </tr>
                        }
                    </table>
                }
            }
        </div>
    </div>

    <div class="py-3">
        <button type="button" class="btn btn-info btn-lg mr-auto" data-toggle="modal" data-target="#AddPrisonerModal">View Complaint History</button>
        <button type="button" class="btn btn-info btn-lg mr-auto" data-toggle="modal" data-target="#AddPrisonerModal">View Transfer History</button>
        <button type="button" class="btn btn-info btn-lg mr-auto" data-toggle="modal" data-target="#AddPrisonerModal">View Visitor History</button>
        <button type="button" class="btn btn-info btn-lg mr-auto" data-toggle="collapse" data-target="#demo" onclick="LoadMedicalRecordsfunction(@Model.Item1.PrisonerID)">View Medical History</button>
    </div>


    <div id="demo" class="collapse">
    </div>

</div>

<script>

    var LoadMedicalRecordsfunction = function (pid) {

        var url = "/Jailer/MedicalRecords?id=" + pid;
        $("#demo").load(url);
    }

</script>

PrisonerMS/Views/Jailer/Transfers.cshtml
@{
    ViewBag.Title = "Transfers";
}

@model List<PrisonerMS.Models.Transfer>

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jailer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "Jailer")">DashBoard</a>
            <a href="@Url.Action("Complaints", "Jailer")">Complaints</a>
            <a href="@Url.Action("Transfers", "Jailer")">Transfers</a>
            <a href="@Url.Action("UserInfo", "Jailer")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Transfers</h3>
        <hr class="hunderline" />

        @if (Model != null)
        {
            <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0">
                <tr>
                    <th>Number</th>
                    <th>Type</th>
                    <th>Type Number</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Entry Date</th>
                    <th>Priosner No</th>
                    <th>Prisoner Name</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><a href="#" onclick="DetailTransferfunction(@item.TransferID)">@item.TransferID</a></td>
                        <td>@item.Type</td>
                        <td>@item.TypeNumber</td>
                        <td>@item.Description</td>
                        <td>@item.Status</td>
                        <td>@item.EntryDate</td>
                        <td><a href=" ../../Jailer/PrisonerDetails?id=@item.Prisoner.PrisonerID">@item.Prisoner.PrisonerNo</a></td>
                        <td>@item.Prisoner.FirstName @item.Prisoner.LastName</td>
                    </tr>
                }
            </table>
        }

        <div class="modal fade" id="detailTransferModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Transfer Detail</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="detailTransferModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>

    var DetailTransferfunction = function (tid) {

        var url = "/Jailer/DetailTransfer?id=" + tid;

        $("#detailTransferModalBodyDiv1").load(url, function () {
            $("#detailTransferModal").modal("show");

        })
    }

</script>

PrisonerMS/Views/Jailer/UserInfo.cshtml
@{
    ViewBag.Title = "UserInfo";
}

@section CustomHeader{
    <nav class="navbar navbar-expand-sm bg-light">

        <a class="navbar-brand" href="#">PMS</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"> Jailer </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (Session["FullName"] != null)
            {
                <p class="navbar-text"> Welcome, @Session["FullName"].ToString() </p>
            }
            <li class="nav-item ml-auto">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Logout </a>
            </li>
        </ul>
    </nav>
}


<div class="row">
    <div class="col-2">
        <div class="sidenav">
            <a href="@Url.Action("DashBoard", "Jailer")">DashBoard</a>
            <a href="@Url.Action("Complaints", "Jailer")">Complaints</a>
            <a href="@Url.Action("Transfers", "Jailer")">Transfers</a>
            <a href="@Url.Action("UserInfo", "Jailer")">Profile</a>
        </div>
    </div>


    <div class="container body-content">
        <h3 class="divheading text-center">Profile</h3>
        <hr class="hunderline" />

        <p><strong>Username : </strong> asad <p>
            <button href="#" type="button" class="btn btn-info" onclick="PasswordChangefunction(1)">Change Password</button>


            <h3 class="divheading text-center">Personal Info</h3>
            <hr class="hunderline" />

        <p><strong>Name : </strong> </p>
        <p><strong>Gender : </strong> Male </p>
        <p><strong>Contact : </strong>03004112112</p>
        <p><strong>DateJoined : </strong>11/11/2019</p>
        <p><strong>Account Status : </strong>Jail Officer</p>
        <button href="#" type="button" class="btn btn-success" onclick="EditInfofunction(1)">Edit Info</button>


        <div class="modal fade" id="changePasswordModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Change Password</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="changePasswordModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="editInfoModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title divheading col-12 text-center">Edit Profile Info</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" id="editInfoModalBodyDiv1">
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>


<script>
    var PasswordChangefunction = function (bid) {

        var url = "/JailO/PasswordChange?id=" + bid;

        $("#changePasswordModalBodyDiv1").load(url, function () {
            $("#changePasswordModal").modal("show");

        })
    }

    var EditInfofunction = function (uid) {

        var url = "/JailO/EditInfo?id=" + uid;

        $("#editInfoModalBodyDiv1").load(url, function () {
            $("#editInfoModal").modal("show");

        })
    }
</script>

PrisonerMS/Views/Jailer/_ComplaintStatus.cshtml
@model int

<div>
    <div class="card rounded px-5 py-2">
        <div class="card-body">
            <form action="UpdateStatus" class="form needs-validation" role="form" autocomplete="off" method="post">

                <input type="hidden" class="form-control" id="C_CompID" name="ComplaintID" value=@Model required />

                <div>
                    <label for="ComplaintStatus">Status</label>
                    <input type="radio" name="ComplaintStatus" value="Placed" required>Placed
                    <input type="radio" name="ComplaintStatus" value="In Process">In Process
                    <input type="radio" name="ComplaintStatus" value="Resolved">Resolved
                    <div class="invalid-feedback">Select Option</div>
                </div>

                <div>
                    <button type="submit" class="btn btn-success float-right">Done</button>
                </div>

            </form>

        </div>
    </div>
</div>

PrisonerMS/Views/Jailer/_DetailMedical.cshtml
@model Tuple<PrisonerMS.Models.Medical, List<PrisonerMS.Models.Medication>, List<PrisonerMS.Models.Allergy>>

<div>
    <div class="card rounded px-2 py-2">
        <div class="card-body">

            <h3>Number: @Model.Item1.MedicalID</h3>
            <p><strong>Symptoms: </strong>@Model.Item1.Symptoms</p>
            <p><strong>Diagnosis: </strong>@Model.Item1.Diagnosis</p>
            <p><strong>Entry Date: </strong>@Model.Item1.EntryDate</p>
            <p><strong>Entry Time: </strong>@Model.Item1.EntryTime</p>

            @if (Model != null)
            {
                if (Model.Item2 != null && Model.Item2.Count != 0)
                {
                    <table id="example1" class="table table-striped table-bordered table-hover" cellspacing="0">
                        <tr>
                            <th>Medication</th>
                            <th>Entry Date</th>
                        </tr>
                        @foreach (var item in Model.Item2)
                        {
                            <tr>
                                <td>@item.Desc</td>
                                <td>@item.EntryDate</td>
                            </tr>
                        }
                    </table>
                }
            }

            @if (Model != null)
            {
                if (Model.Item3 != null && Model.Item3.Count != 0)
                {
                    <table id="example2" class="table table-striped table-bordered table-hover" cellspacing="0">
                        <tr>
                            <th>Allergy</th>
                            <th>Entry Date</th>
                        </tr>
                        @foreach (var item in Model.Item3)
                        {
                            <tr>
                                <td>@item.Desc</td>
                                <td>@item.EntryDate</td>
                            </tr>
                        }
                    </table>
                }
            }

        </div>
    </div>
</div>

PrisonerMS/Views/Jailer/_DetailTransfer.cshtml
@model PrisonerMS.Models.Transfer

<div>
    <div class="card rounded px-5 py-2">
        <div class="card-body">

            <h3> @Model.TransferID </h3>
            <p><strong>Type: </strong>@Model.Type</p>
            <p><strong>Type Number: </strong>@Model.TypeNumber</p>
            <p><strong>Description: </strong>@Model.Description</p>
            <p><strong>Status: </strong>@Model.Status</p>
            <p><strong>Entry Date: </strong>@Model.EntryDate</p>
            <p><strong>Entry Time: </strong>@Model.EntryTime</p>
            <p><strong>Prisoner Number: </strong>@Model.Prisoner.PrisonerNo</p>
            <p><strong>Prisoner First Name: </strong>@Model.Prisoner.FirstName</p>
            <p><strong>Prisoner Last Name: </strong>@Model.Prisoner.LastName</p>
            <p><strong>Prison Number: </strong>@Model.Prison.PNumber</p>
            <p><strong>Prison Name: </strong>@Model.Prison.Name</p>

            <button type="button" class="btn btn-info" onclick="location.href = '../../Jailer/PrisonerDetails?id=@Model.Prisoner.PrisonerID';">View Prisoner</button>
        </div>
    </div>
</div>